os: osx
osx_image: xcode10.2

language: bash

before_cache:
 - brew cleanup
 
cache:
 - directories:
  - $HOME/Library/Caches/Homebrew

before_install:
  - whoami
  - echo "start of pipeline"
  - HOMEBREW_No_AUTO_UPDATE=1

script:
 - echo "hello script!"
 - ls
 - chmod +x hello.sh
 - ./hello.sh

after_script:
  - echo "End of pipeline"




